site_name: Philippe Berset
site_url: https://sukori.github.io/technophil.ch/
site_description: Homepage et portfolio personnel de Philippe Berset
site_author: Philippe Berset
repo_url: https://github.com/Sukori/technophil.ch
nav:
  - Accueil: index.md
  - Qui suis-je ?: about.md
theme:
  name: material
  features:
    - navigation.tabs
    - toc.integrate
    - navigation.top