site_name: Philippe Berset
site_url: https://technophil.dev/
site_description: Homepage et portfolio personnel de Philippe Berset
site_author: Philippe Berset
repo_url: https://github.com/Sukori/technophil.dev
#nav:
#  - Accueil: index.md
#  - Qui suis-je ?: about.md
#  - Projets: projects.md
theme:
  name: material
  features:
    - navigation.tabs
    - toc.integrate
    - navigation.top

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  alternate:
    - name: English
      link: ./en/
      lang: en
    - name: Français
      link: ./
      lang: fr

nav:
  - index.md
  - about.md
  - projects.md

plugins:
  - search
  - i18n:
      default_language: fr
      languages:
        en: english
        fr: français
      nav_translations:
        en:
          - index.en.md
          - about.en.md
          - projects.en.md